pipeline {
    agent { label '!windows' }
    stages {
        stage('SonarQube') {
            steps {
                script { scannerHome = tool 'Hive-scanner' }
                withSonarQubeEnv('SonarQube') {
                    sh "${scannerHome}/bin/sonar-scanner -Dsonar.projectKey=[key]"
                }
            }
        }
    }
}